---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data

```{r, echo=TRUE}
con <- unz("activity.zip", "activity.csv")
data <- read.csv(con)
```

## What is mean total number of steps taken per day?

```{r, echo=TRUE}
stepsByDay <- aggregate(steps ~ date, data, sum)

hist(stepsByDay$steps, xlab="Steps", main="Steps by day")

sprintf("Mean amount of steps: %.2f", mean(stepsByDay$steps))
sprintf("Median amount of steps: %d", median(stepsByDay$steps))
```


## What is the average daily activity pattern?

```{r, echo=TRUE}
stepsByInterval <- aggregate(steps ~ interval, data, mean)

plot(stepsByInterval$interval, stepsByInterval$steps, type="l", xlab="Interval", ylab="Steps", main="Steps by 5-minutes interval, averaged across all days")

maxNumberOfSteps <- max(stepsByInterval$steps)

sprintf("Interval %d contains maximum number of steps: %.2f", with(stepsByInterval, subset(interval, steps==maxNumberOfSteps)), maxNumberOfSteps)
```


## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
